### ISSUE TITLE
[To Do] Kibana currently opens in a new tab, it should open embedded

### ISSUE THREAD

**Issue by archaeogeek** [AstunTechnology/os-custom-geonetwork#1]
If you visit admin console -> statistics and status -> content statistics, kibana (dashboarding) should open in the same browser tab but in firefox at least, it opens in a new tab. There's a fix for this!

**Comment by howaskew** [comment]
![image](https://user-images.githubusercontent.com/19271569/105860496-8e087300-5fe5-11eb-841c-c1d8a397b7b3.png)

In Edge browser on Windows 10, I get this message, and no new tab opens.

**Comment by archaeogeek** [comment]
Not actually applied yet!

**Comment by howaskew** [comment]
Oh sorry!
