### ISSUE TITLE
[Documentation Request]: Summarise configuration and customisation changes made to default geonetwork

### ISSUE THREAD

**Issue by howaskew** [AstunTechnology/os-custom-geonetwork#5]
As discussed, please can you summarise the changes made for example...

## Configuring and customising the portal

* The following changes are made via the admin console to customise the default geonetwork install (plus the Gemini 2.3 plugin):
   * Rename catalogue
   * Upload OS logo and fav-icon
   * Enable INSPIRE
   * Import Gemini 2.3 templates
   * Add the INSPIRE service taxonomy: http://geonetwork-opensource.org/inspire-service-taxonomy
   * Add the GEMET - INSPIRE themes: http://inspire.ec.europa.eu/theme
   * Add the GEMET concept thesaurus: http://geonetwork-opensource.org/gemet
   *

**Comment by archaeogeek** [comment]
https://github.com/AstunTechnology/os-custom-geonetwork/wiki/Configuring-and-customising-the-portal please add any further configuration changes that you make to that page.
