### ISSUE TITLE
[Documentation Request]: Adding metadata elements (from Gemini 2.3)

### ISSUE THREAD

**Issue by howaskew** [AstunTechnology/os-custom-geonetwork#7]
From the 2.3 template. If I'm trying to add data quality metadata, from the drop down I can choose e.g.
![image](https://user-images.githubusercontent.com/19271569/105862802-1c7df400-5fe8-11eb-841f-07c827211294.png)
And then get this...
![image](https://user-images.githubusercontent.com/19271569/105862931-433c2a80-5fe8-11eb-9e06-1408427f893b.png)
But can't seem to add any details.
Is that a bug or am I missing something?

**Comment by archaeogeek** [comment]
Yes and no- for built-in data quality reports use the search box to the right of what you've selected there to pull in inspire ones (see https://osmetadata.astuntechnology.com/geonetwork/srv/eng/catalog.edit#/directory for the list so far). The rest of this is to follow in the knowledge transfer for WP2 but was marked as lower priority.
