### ISSUE TITLE
[Documentation Request]: Deleted Conformity Element

### ISSUE THREAD

**Issue by nicolevf** [AstunTechnology/os-custom-geonetwork#8]
Invalid records due to missing conformity element, which I deleted by accident and now can't bring back. 
<img width="407" alt="Screenshot 2021-01-29 174221" src="https://user-images.githubusercontent.com/50834401/106309000-6a4d6300-6259-11eb-93ae-a5de2706dfbb.png">

**Comment by archaeogeek** [comment]
@nicolevf which record is causing problems for you?

**Comment by archaeogeek** [comment]
I've created a little gif to show what you should be seeing if there's no conformity section. Let me know if it helps/doesn't help and what record is causing issues
![Peek 2021-02-01 14-12](https://user-images.githubusercontent.com/1544849/106469840-b71e7d00-6497-11eb-8104-aa7cd28cd209.gif)

**Comment by PeterParslow** [comment]
That's neat; I was just looking for that.

A bit of an aside, the snippet pasted in raises a suggestion / improvement tip on validation, that the first two words in the citation are capitalised wrong, and should be "Commission Regulation".

**Comment by archaeogeek** [comment]
@PeterParslow thanks, interesting- I'll look into that as the INSPIRE TG definitely have it fully capitalised afaict? Can we confirm whether this fixes the original issue @nicolevf reported?

**Comment by PeterParslow** [comment]
Good spot, Jo. I can't remember (or find) why GEMINI differs from the examples in the INSPIRE TG on capitalisation.

**Comment by archaeogeek** [comment]
I'm following it through- I have a suspicion it's something in the ISO19139 GeoNetwork implementation rather than something explicitly stated in the Gemini implementation but I might be wrong!

**Comment by nicolevf** [comment]
Hi Jo, yes all fixed - mostly user error so very helpful thanks!

**Comment by archaeogeek** [comment]
@nicolevf thanks for letting me know, I'll close this then
